### ISSUE TITLE
Build failed on macOS: Exec format error

### ISSUE THREAD

**Issue by Jason5Lee** [unoplatform/Uno.CodeGen#132]
## Build failed on macOS

When I build a project, the following error message is shown.

```
/Users/Username/.nuget/packages/uno.sourcegenerationtasks/1.31.0/build/netstandard1.0/Uno.SourceGenerationTasks.targets(122,2): error : Exec format error [/Users/Username/Code/ScriptSharp/ScriptCSharp/ScriptCSharp.csproj]
```

OS: macOS Catalina 10.15.7
.NET Core version: 3.1.402

**Comment by jeromelaban** [comment]
Thanks for the report. You'll need to install Uno.Sourcegeneration tasks 2.0 or later.
