### ISSUE TITLE
Update Uno.SourceGeneration and Uno SourceGenerationTasks

### ISSUE THREAD

**Issue by carlh98** [unoplatform/Uno.CodeGen#136]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

Uno.SourceGeneration and Uno.SourceGenerationTasks are at version 1.30.0-dev.245 which caused package downgrade in current projects

## Expected behavior

Uno.SourceGeneration and Uno SourceGenerationTasks needs to be at version 3.1.0

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s): All platforms
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

**Comment by carlh98** [comment]
@jeromelaban This is the issue blocking @Iguins

**Comment by carlh98** [comment]
Related : https://github.com/unoplatform/Uno.CodeGen/pull/135

**Comment by jeromelaban** [comment]
There should not be any downgrade, as those a transitive dependencies. You probably do have to specify the version explicitly in your project, as both Uno and Uno.Codegen specify a version transitively.
